version: '3.1'
services:
  db:
    image: postgres:13
    container_name: db_M7_2425
    environment:
      - POSTGRES_DB=postgres_24255
      - POSTGRES_PASSWORD=pass_postgres1
      - POSTGRES_USER=user_postgres1
    ports:
      - "5433:5432" # Cambiado de 5432 a 5433
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_M7_2425
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: roger@xtec.cat
      PGADMIN_DEFAULT_PASSWORD: roger123
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  local_pgdata:
  pgadmin-data: